export interface ProblemDetails {
    /** A URI reference that identifies the problem type (defaults to "about:blank") */
    type?: string
    /** A short, human-readable summary of the problem type */
    title?: string
    /** The HTTP status code generated by the origin server */
    status?: number
    /** A human-readable explanation specific to this occurrence of the problem */
    detail?: string
    /** A URI reference that identifies the specific occurrence of the problem */
    instance?: string
}

export default ProblemDetails;
